name: Testnet CI/CD
on:
  push:
    branches:
    # Executes on any non master commit, but release and deploy steps only run on development
    # This is useful to see if tests are passing during PR review
    - '**'
    - '!master'
    paths-ignore:
    - 'monitoring/**'
    - 'emails/**'
env:
  REPO: celeste-backend/rinkeby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $REPO:${GITHUB_SHA}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - run: .github/scripts/test/run.sh $REPO:${GITHUB_SHA}
      
