name: Testnet CI/CD
on:
  push:
    branches:
    # Executes on any non master commit, but release and deploy steps only run on development
    # This is useful to see if tests are passing during PR review
    - '**'
    - '!master'
    paths-ignore:
    - 'monitoring/**'
    - 'emails/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/1hive/celeste-backend-rinkeby:latest
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - run: .github/scripts/test/run.sh ghcr.io/1hive/celeste-backend-rinkeby:latest


  deploy:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh court-backend-rinkeby ghcr.io/1hive/celeste-backend-rinkeby:latest
    # - run: .github/scripts/kubectl-wait-ready.sh court-backend-rinkeby
    # wait 10 sec for k8s to reroute ingress and check app endpoint
    # - run: sleep 10 && curl --fail https://court-app-rinkeby.backend.aragon.org
      
